

const Countries:string[]=["US"];
const States:{country:string,state:string}[]=[{country:"US", state:  "Alabama"},
{country:"US", state:  "Alaska"},
{country:"US", state:  "Arizona"},
{country:"US", state:  "Arkansas"},
{country:"US", state:  "California"},
{country:"US", state:  "Colorado"},
{country:"US", state:  "Connecticut"},
{country:"US", state:  "Delaware"},
{country:"US", state:  "District Of Columbia"},
{country:"US", state:  "Florida"},
{country:"US", state:  "Georgia"},
{country:"US", state:  "Hawaii"},
{country:"US", state:  "Idaho"},
{country:"US", state:  "Illinois"},
{country:"US", state:  "Indiana"},
{country:"US", state:  "Iowa"},
{country:"US", state:  "Kansas"},
{country:"US", state:  "Kentucky"},
{country:"US", state:  "Louisiana"},
{country:"US", state:  "Maine"},
{country:"US", state:  "Maryland"},
{country:"US", state:  "Massachusetts"},
{country:"US", state:  "Michigan"},
{country:"US", state:  "Minnesota"},
{country:"US", state:  "Mississippi"},
{country:"US", state:  "Missouri"},
{country:"US", state:  "Montana"},
{country:"US", state:  "Nebraska"},
{country:"US", state:  "Nevada"},
{country:"US", state:  "New Hampshire"},
{country:"US", state:  "New Jersey"},
{country:"US", state:  "New Mexico"},
{country:"US", state:  "New York"},
{country:"US", state:  "North Carolina"},
{country:"US", state:  "North Dakota"},
{country:"US", state:  "Ohio"},
{country:"US", state:  "Oklahoma"},
{country:"US", state:  "Oregon"},
{country:"US", state:  "Pennsylvania"},
{country:"US", state:  "Rhode Island"},
{country:"US", state:  "South Carolina"},
{country:"US", state:  "South Dakota"},
{country:"US", state:  "Tennessee"},
{country:"US", state:  "Texas"},
{country:"US", state:  "Utah"},
{country:"US", state:  "Vermont"},
{country:"US", state:  "Virginia"},
{country:"US", state:  "Washington"},
{country:"US", state:  "West Virginia"},
{country:"US", state:  "Wisconsin"},
{country:"US", state:  "Wyoming"}]
export default {Countries,States}