# Variable 'apiKey' was defined in the Variables tab
# Variable 'userKey' was defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/devlopment
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/devlopment
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    displayName: Use Python 3.9
    inputs:
      versionSpec: 3.9
  - task: Bash@3
    displayName: Build extensions
    inputs:
      targetType: inline
      script: >-
        if [ -f extensions.csproj ]

        then
            dotnet build extensions.csproj --output ./bin
        fi
  - task: Bash@3
    displayName: Install Application Dependencies
    inputs:
      targetType: inline
      script: pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: tada-compute-drop'
    inputs:
      ArtifactName: tada-compute-drop
  - task: CmdLine@2
    displayName: Download the Unified Jar
    inputs:
      script: >
        curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
  - task: CmdLine@2
    displayName: Run Unified Agent.jar
    inputs:
      script: >
        java -jar wss-unified-agent.jar -c wss-unified-agent.config -apikey $(apikey) -userkey $(userkey)
...
